spring:
  application:
    name: admin-server
  profiles:
    active:
    - secure
server:
    port: 8300

# tag::configuration-eureka[]
eureka:   #<1>
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    metadata-map:
      startup: ${random.int}    #needed to trigger info and endpoint update after restart
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://${spring.security.user.name}:${spring.security.user.password}@127.0.0.1:8400}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"  #<2>
  endpoint:
    health:
      show-details: ALWAYS
# end::configuration-eureka[]

---
spring:
  profiles: insecure

---
spring:
  profiles: secure
  mail:
    host: smtp.163.com
    username: leolinsy@163.com
    password: 111111
    properties:
      mail.debug: false
      mail.stmp.auth: true
  boot:
    admin:
      notify:
        mail:
          to: 1111@111.com
          cc: leolinsy@163.com
          from: leolinsy@163.com
  security:
    user:
      name: root
      password: cx
#      roles: "SUPERUSER"
eureka:
  instance:
    metadata-map:
      user.name: root        #These two are needed so that the server
      user.password: cx #can access the protected client endpoints

